### PR TITLE
feat(init): save project_id in config

### PR DESCRIPTION
**Pull request by QuentinBrosse**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/scaleway/scaleway-cli/blob/v2/CHANGELOG.md):

```release-note
Save the `project_id` in the config with the `scw init` command
```

### CODE REVIEW

**Review by jerome-quere — APPROVED** [review]
LGTM

**Review by remyleone — APPROVED** [review]

**Comment by jerome-quere** [comment]
Do we have test for init ? Should we add a test for this ?

**Comment by QuentinBrosse** [comment]
> Do we have test for init ? Should we add a test for this?

@jerome-quere in this precise use-case it's complex to test as we need to test the behavior where the `scw init` will automatically get the `access_key`, `organization_id`, `project_id`, ... from the account API. It will require to moke the account API but without cassettes to get a consistent result and test this result.
I think that's why [we only check the `secret_key` in the "Override" test](https://github.com/scaleway/scaleway-cli/blob/master/internal/namespaces/init/init_test.go#L144).

**Review by jerome-quere — APPROVED** [review]
LGTM

**Pull request merged**
