### PR TITLE
Feature billing

### PR DESCRIPTION
**Pull request by moul**
This is the initial version of billing, it's not yet complete and result is approximative but already useful, and this is a good start to iterate over new features and improvements in the future

### CODE REVIEW

**Comment by moul** [comment]
https://travis-ci.org/scaleway/scaleway-cli/jobs/78211984#L496-L607

**Comment by moul** [comment]
Actual output example:

```console
➜  ~  scw _billing
WARN[0000]
WARN[0000] Warning: 'scw _billing' is a work-in-progress price estimation tool
WARN[0000] For real usage, visit https://cloud.scaleway.com/#/billing
WARN[0000]
ID                  NAME                        STARTED             MONTH PRICE
server/1efc3a59     suspicious-bhabha           18 hours            0.038 EUR
server/23dd3649     gloomy-mclean               29 hours            0.06 EUR
server/f917ac87     lonely-turing               44 hours            0.09 EUR
server/b40f3033     sick-sammet                 44 hours            0.09 EUR
server/d92c42c7     hungry-morse                44 hours            0.09 EUR
server/587d1528     trusting-leakey             44 hours            0.09 EUR
server/c3afc0b9     drunk-pike                  47 hours            0.096 EUR
server/0d64910e     angry-shockley              47 hours            0.096 EUR
server/5b9c4891     dreamy-galileo              47 hours            0.096 EUR
server/ab4996e2     tender-colden               2 days              0.1 EUR
server/685e25ee     trusting-bartik             2 days              0.1 EUR
server/4b55ba4a     modest-lumiere              2 days              0.1 EUR
server/6d2d7538     modest-meitner              2 days              0.1 EUR
server/e5852128     reverent-mestorf            2 days              0.102 EUR
server/eac6a919     angry-brattain              2 days              0.104 EUR
server/6a64a0bf     pensive-bohr                2 days              0.104 EUR
server/16483b1f     determined-hawking          2 days              0.142 EUR
server/88fec3fa     determined-engelbart        3 days              0.192 EUR
server/86fa35ba     boring-bohr                 3 days              0.192 EUR
server/f627dbf1     distracted-franklin         3 days              0.192 EUR
server/1a2a78b5     hungry-archimedes           4 days              0.224 EUR
server/75a2811d     kickass-ardinghelli         4 days              0.224 EUR
server/a8db7066     thirsty-ardinghelli         4 days              0.224 EUR
server/f056b955     admiring-goodall            4 days              0.234 EUR
server/6213b608     adoring-kirch               4 days              0.234 EUR
server/1fe97d42     live_scw-distrib-ubuntu-v   4 days              0.236 EUR
server/84fb9d14     live_scw-distrib-ubuntu-v   4 days              0.236 EUR
server/834ca204     sick-kilby                  4 days              0.238 EUR
server/b6d36381     serene-meitner              4 days              0.238 EUR
server/9cabf2b5     naughty-elion               4 days              0.238 EUR
server/adf39c0f     fervent-yalow               4 days              0.238 EUR
server/1a9c3d94     romantic-panini             6 days              0.29 EUR
server/5484a0c7     thirsty-torvalds            6 days              0.29 EUR
server/3be6d918     sick-pasteur                6 days              0.3 EUR
server/429dfc62     image-writer-scw-distrib-   8 days              0.426 EUR
server/5a3f2d41     image-writer-scw-distrib-   8 days              0.426 EUR
server/85e102ec     image-writer-scw-distrib-   8 days              0.426 EUR
server/72440d12     distracted-elion            8 days              0.426 EUR
server/27822907     jolly-brahmagupta           9 days              0.434 EUR
server/c2249efa     goofy-poitras               9 days              0.442 EUR
server/857620b9     clever-yalow                9 days              0.442 EUR
server/b025cd24     hungry-chandrasekhar        9 days              0.444 EUR
server/cee2a98b     pensive-tesla               9 days              0.444 EUR
server/dd3a760e     sad-babbage                 9 days              0.444 EUR
server/cdc3c19c     goofy-carson                9 days              0.444 EUR
server/f33872ae     fervent-cray                9 days              0.444 EUR
server/56abe3d8     stoic-kowalevski            9 days              0.444 EUR
server/0b2a9038     ecstatic-pare               9 days              0.444 EUR
server/b6d11a21     dreamy-aryabhata            9 days              0.444 EUR
server/17a7becf     grave-ardinghelli           9 days              0.444 EUR
server/7cda0d95     hungry-thompson             9 days              0.444 EUR
server/ce85ffa0     grave-cori                  9 days              0.478 EUR
server/8f17cd7a     bitrig-build                10 days             0.49 EUR
server/2184793d     3_torrents_m_42_am          10 days             0.52 EUR
server/a995caf6     wireguard-docker            11 days             0.546 EUR
server/08bcea8a     wireguard-gentoo            11 days             0.546 EUR
server/424d63ae     voidlinux-builder           11 days             0.57 EUR
server/4be593b2     mad-mestorf                 6 days              0.29 EUR
server/d80fbfc0     dreamy-cray                 6 days              0.29 EUR
server/758213db     thirsty-einstein            6 days              0.3 EUR
server/bb3f8072     evil-darwin                 6 days              0.3 EUR
server/5ed9ba9b     hungry-visvesvaraya         6 days              0.3 EUR
server/30cd0b4b     nostalgic-kirch             6 days              0.3 EUR
server/dbe4ca14     stoic-wilson                6 days              0.3 EUR
server/e26d4330     romantic-turing             6 days              0.3 EUR
server/4b4da255     jolly-lalande               6 days              0.3 EUR
server/aab864e2     romantic-bohr               6 days              0.3 EUR
server/56f996fe     syncthing_m_42_am           9 weeks             1 EUR
server/8faf70d1     docker-builder-7            11 weeks            1 EUR
server/371a34d1     bitrig-bbb                  11 weeks            1 EUR
server/ef7bf54c     bitrig-aaa                  11 weeks            1 EUR
server/f03a08a8     docker-builder-6            11 weeks            1 EUR
server/f8b15e3d     torrents-4                  11 weeks            1 EUR
server/bc97dba6     bitrig-ccc                  5 weeks             1 EUR
server/2574fdb0     VAIPAIHAINE                 12 weeks            1 EUR
server/72371150     mutu-perf                   3 months            1 EUR
server/f5c44179     2_torrents_m_42_am          3 months            1 EUR
server/06378619     torrents_m_42_am            3 months            1 EUR
server/4275e304     rescue_distrib-alpine-lat   4 months            1 EUR
TOTAL                                                               31.21 EUR
```

**Comment by moul** [comment]
cc @kdeldycke

**Comment by QuentinPerez** [comment]
LGTM

**Comment by moul** [comment]
I created a new issue here that will complements the current PR with long-term features, so we can merge this initial version quickly and iterates more easily

https://github.com/scaleway/scaleway-cli/issues/169

**Comment by aimxhaisse** [comment]
lgtm

**Pull request merged**
