### PR TITLE
Add detection of main volume size before creating additional volumes

### PR DESCRIPTION
**Pull request by ViViDboarder**
With the current implementation the api will force the creation of
additional volumes to meet the minimum per instance type regardless of
the primary volume size. This causes an issue if the primary volume is
larger than 50G

This patch will compare the primary volume to the min sizes

This expands upon #403 provides a slightly more flexible fix for #361 that also resolves scaleway/image-builder#14

### CODE REVIEW

**Comment by brmzkw** [comment]
Hi,

Thanks a lot for your pull request.

At Scaleway, we internally maintain a JSON file which describes our offers. It is available [here as a Github gist](https://git.io/vH6Uk). It will probably be exposed by our APIs in a near future.

This JSON file contains:

* the commercial names of our offers : the top level key in the dict. Some products also have alternative names. For instance, "VC1S" describes the same server than "X64-2GB".
* some hardware details: number of CPUs, RAM, NICs, ...
* and more importantly in the context of this PR: the volumes constraints, ie. the minimal/maximal volumes sizes to create a server of a given type.

Don't you think we should go further, and:

* add this JSON file in the scaleway-cli repository
* someway parse and use it to create servers

?

I'm not a golang expert, so I'm not sure of the best way to integrate such a file though.

**Comment by ViViDboarder** [comment]
Oh, that would be very nice!

Golang has some great built in ways to marshal and unmarshal JSON, so parsing this would be very easy. It then seems easy enough to use the returned map to get the volume constraints.

My only concern with doing it here would be that it maybe confusing if it's not used everywhere. Also, the compiling the JSON into the binary might be non-trivial.

Given that... if there was an API available, it might be easier/better to query the restrictions and offerings from that API. That would allow adding and removing of offerings from your server-side without client changes.

**Comment by brmzkw** [comment]
Here we are, I updated our compute APIs:

* https://cp-par1.scaleway.com/products/servers
* https://cp-ams1.scaleway.com/products/servers

Note the C1 servers are not available in Amsterdam.

If you want to include these new APIs in scaleway-cli, I'd be glad to accept the pull request. Otherwise I'll probably work on it sooner or later.

**Comment by brmzkw** [comment]
@tbillon : I think this PR can be closed, isn't it? Correct me if I'm wrong, but I think we only have to release scaleway-cli.

**Comment by tbillon** [comment]
Yes it can probably be closed. My previous commit should do the trick.

**Comment by brmzkw** [comment]
But since @tbillon implemented a dynamic version to find the volumes to create for a given instance, we will go with his version instead.

Again, thanks a lot for your contribution @ViViDboarder

**Pull request closed without merging**
