### PR TITLE
Fix #194 1/2

### LINKED ISSUE #194: When connecting using SSH, check if host keys are available in the userdata
Depends on: https://github.com/scaleway/image-tools/issues/36

If the host keys are available you can : 

- [ ] display fingerprints
- [ ] register fingerprint on the local host (ssh-keygen) + remove this: https://github.com/scaleway/scaleway-cli/blob/master/pkg/utils/utils.go#L83

I suggest you to begin with 1 as the userdata API is still very young and most of the actual images won't have scripts that generates the fingerprints

### PR DESCRIPTION
**Pull request by QuentinPerez**
fix #194

### CODE REVIEW

**Comment by moul** [comment]
Needs a rebase

**Comment by QuentinPerez** [comment]
Done :)

**Comment by moul** [comment]
I think we will need a message before printing out all the keys, but I have no idea for now, so lets merge it and find by using this new feature

**Comment by moul** [comment]
LGTM

**Pull request merged**
