### PR TITLE
Add back Chocolatey.

### PR DESCRIPTION
**Pull request by thorerik**
This adds back the Cocolatey package manager note.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/scaleway/scaleway-cli/blob/master/CHANGELOG.md):

```release-note

```

### CODE REVIEW

**Review by Sh4d1 — COMMENTED** [review]
LGTM, maybe could you add in the README that you are the maintainer? @remyleone wdyt?

**Comment by remyleone** [comment]
The maintainer information is already present on the page of chocolatey: https://chocolatey.org/packages/scaleway-cli I would prefer if we would put a link to this page directly

**Comment by thorerik** [comment]
Also, if any of the people at Scaleway would like to have access, let me know

**Review by Sh4d1 — APPROVED** [review]
LGTM

**Comment by remyleone** [comment]
@thorerik could you add me with administrative privileges? I'm remyleone on the chocolatey platform.

**Pull request merged**
