### PR TITLE
Enable creation of public IP-less servers via special IP address names

### PR DESCRIPTION
**Pull request by ElNounch**

### CODE REVIEW

**Comment by moul** [comment]
Thank you @ElNounch, it looks good to me


@QuentinPerez, can you give a try tomorrow to see if every cases are handled ?

We will also need to:

* Update the Changeloga
* Add usage examples in `README.md`
* Add usage examples in `scw create -h`
* Port this to `scw run` too

**Comment by QuentinPerez** [comment]
Tested and LGTM 😃

**Comment by ElNounch** [comment]
Commited port to `scw run` in what should be a retro-compatible way.

**Comment by QuentinPerez** [comment]
Thank you @ElNounch 😉

**Comment by moul** [comment]
@QuentinPerez, can you update the Changelog ?

**Pull request merged**
