### PR TITLE
Improve _cs format

### PR DESCRIPTION
**Pull request by QuentinPerez**
#223
```console
$> ./scw _cs
s3://datas
$> ./scw _cs datas
2015-10-07 11:28    310kB s3://datas/text.txt
2015-10-07 11:28    100kB s3://datas/binaire
```

### CODE REVIEW

**Comment by moul** [comment]
can you also require a "s3://" prefix when using a path ?

```console
$> ./scw _cs
s3://datas
$> ./scw _cs s3://datas
2015-10-07 11:28    310kB s3://datas/text.txt
2015-10-07 11:28    100kB s3://datas/binaire
```

**Comment by QuentinPerez** [comment]
Yes

**Comment by moul** [comment]
LGTM

**Comment by moul** [comment]
no sorry, update the README.md please

**Comment by moul** [comment]
Can you make a `party -c -t -d=vendor` in a separated commit ?

**Pull request merged**
