### PR TITLE
Introduce Logger

### PR DESCRIPTION
**Pull request by nicolai86**
Following #368 this PR introduces a `Logger` interface which allows us to extract the `http2curl` and `logrus` dependencies into the `cli` & `command` packages.

The `Logger` contains two functions - `LogHTTP` to handle `http.Request`, and `Log` for plain `string`.
The `cli` configures the `ScalewayAPI` instance to retain the old logging behaviour. By default, the logging is not very verbose, logging only messages & API endpoints being used.

Also, I've replaced `anonuuid` with static, fake uuids. Not sure why we need "randomized" uuids if the only concern is to sanitize logs from real credentials.

### CODE REVIEW

**Comment by nicolai86** [comment]
@QuentinPerez thanks for improving the PR!

**Comment by QuentinPerez** [comment]
LGTM, ping @moul 😊

**Comment by moul** [comment]
LGTM, thank you

**Comment by moul** [comment]
Well done guys

**Comment by moul** [comment]
@QuentinPerez can you credit @nicolai86 in the changelog ?

**Comment by nicolai86** [comment]
Thanks for being so responsive! I'll continue my quest to get scaleway into terraform, then. 🙏🏼

**Comment by nicolai86** [comment]
For those interested in the terraform provider, you can take a look here: https://github.com/hashicorp/terraform/pull/7331

**Pull request merged**
